### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by kendonB** [synkarius/tirg-dll#3]
Hi there, I'm trying to understand all the dependencies for Caster. Are you able to give an idea of how to compile these files into a `.dll`? I had a go using this `Makefile` and MingW32:

```
all: tirg-dll.dll

tirg-dll.dll: tirg_raw.cpp
	/usr/bin/g++ -static-libgcc -o tirg-dll.dll -shared tirg_raw.cpp -Wall
```

**Comment by kendonB** [comment]
Once I move the resultant dll into caster, I get this:

```
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\dragonfly\actions\action_function.py", line 136, in _execute
    self._function(**arguments)
  File "C:\Users\kmbel\Documents\caster\castervoice\lib\navigation.py", line 70, in mouse_alternates
    ls = LegionScanner()
  File "C:\Users\kmbel\Documents\caster\castervoice\asynch\mouse\legion.py", line 161, in __init__
    self.setup_dll()
  File "C:\Users\kmbel\Documents\caster\castervoice\asynch\mouse\legion.py", line 171, in setup_dll
    sys.getfilesystemencoding()))
  File "C:\Python27\Lib\ctypes\__init__.py", line 444, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python27\Lib\ctypes\__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 193] %1 is not a valid Win32 application
ERROR:action.exec:Execution failed: Function(mouse_alternates): [Error 193] %1 is not a valid Win32 application
```
whenever I say "legion". Help?

**Comment by kendonB** [comment]
@mrob95 @LexiconCode, fyi

**Comment by kendonB** [comment]
I also removed the header `#include "stdafx.h"`

**Comment by kendonB** [comment]
okay I figured out after pulling out the old Visual Studio project files from older commits then building with "Release" in Visual Studio Community 2019.

**Comment by kendonB** [comment]
it actually seems to run a little faster

**Comment by LexiconCode** [comment]
@kendonB Do you think this is compatible with Python 3 64-bit? We may need to compile a 64-bit version if that's easily done.
Notes [Configuring Visual Studio Community for 64-bit compile](https://docs.microsoft.com/en-us/cpp/build/how-to-configure-visual-cpp-projects-to-target-64-bit-platforms?view=vs-2019)

I'm getting a very similar traceback as you posted earlier.
```
Traceback (most recent call last):
  File "G:\p3_kaldi-caster-winpython-dev2\winpython\python-3.7.4.amd64\lib\site-packages\dragonfly\actions\action_function.py", line 136, in _execute
    self._function(**arguments)
  File "G:\p3_kaldi-caster-winpython-dev2\caster\castervoice\lib\navigation.py", line 71, in mouse_alternates
    ls = LegionScanner()
  File "G:\p3_kaldi-caster-winpython-dev2\caster\castervoice\asynch\mouse\legion.py", line 166, in __init__
    self.setup_dll()
  File "G:\p3_kaldi-caster-winpython-dev2\caster\castervoice\asynch\mouse\legion.py", line 175, in setup_dll
    str(settings.SETTINGS["paths"]["DLL_PATH"] + "tirg-dll.dll")).encode(
  File "G:\p3_kaldi-caster-winpython-dev2\winpython\python-3.7.4.amd64\lib\ctypes\__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "G:\p3_kaldi-caster-winpython-dev2\winpython\python-3.7.4.amd64\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application
ERROR:action.exec:Execution failed: Function(mouse_alternates): [WinError 193] %1 is not a valid Win32 application
```

**Comment by LexiconCode** [comment]
I think I was able to get it to compile a 64-bit version. Although I'm still working through other Python 3 issues with Legion. So testing will be in the future.

**Comment by LexiconCode** [comment]
This issue should be resolved in https://github.com/synkarius/tirg-dll/pull/4
